name: Build Nuxt

on:
  create:
  workflow_dispatch:

# 必须加权限！否则不能上传 Release
permissions:
  contents: write

jobs:
  build:
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'create' && github.event.ref_type == 'tag')
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20.20.0
        uses: actions/setup-node@v4
        with:
          node-version: 20.20.0
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Prepare artifact
        run: |
          mkdir -p release
          cp -r .output release/.output
          cp package.json release/
          if [ -f package-lock.json ]; then
            cp package-lock.json release/
          fi

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: nuxt-linux-build-${{ github.sha }}
          path: release
          include-hidden-files: true
          retention-days: 7

      # ===================== 下面是新增的关键代码 =====================
      - name: Package release zip
        if: github.event_name == 'create' && github.event.ref_type == 'tag' # 只有创建 tag 才执行
        run: |
          cd release
          zip -r ../nuxt-app.zip .

      - name: Upload to GitHub Release
        if: github.event_name == 'create' && github.event.ref_type == 'tag' # 只有创建 tag 才执行
        uses: softprops/action-gh-release@v2
        with:
          files: nuxt-app.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
